export const FRIENDS_GET_SUCCESS = 'FRIENDS_GET_SUCCESS';
export const MESAGE_GET_SUCCESSS = 'MESAGE_GET_SUCCESSS';
export const MESSAGE_SEND_SUCCESS = 'MESSAGE_SEND_SUCCESS';
export const SOCKET_MESSAGE = 'SOCKET_MESSAGE';