export const FRIENDS_GET_SUCCESS = 'FRIENDS_GET_SUCCESS';
export const MESSAGE_GET_SUCCESS = 'MESSAGE_GET_SUCCESS';
export const MESSAGE_SEND_SUCCESS = 'MESSAGE_SEND_SUCCESS';
export const SOCKET_MESSAGE = 'SOCKET_MESSAGE';
export const UPDATE_FRND_SMS = 'UPDATE_FRND_SMS';
export const SEEN_SMS = 'SEEN_SMS';
export const DELIVERED_SMS = 'DELIVERED_SMS';
export const UPDATE = 'UPDATE';